version: '3.8'
services:
    mongo:
        image: mongo:6.0-focal
        container_name: electric-mongo-dev
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:7
        container_name: electric-redis-dev
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    mongo-data:
    redis-data:
