version: '3.8'
services:
    mongo:
        image: mongo:6.0-focal
        container_name: nghiavanec-mongo-dev
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db

    redis:
        image: redis:7
        container_name: nghiavanec-redis-dev
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - ./redisdata:/data
